name: create-release
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install Pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-linux-amd64.tar.gz
          tar -zxvf pandoc-2.18-linux-amd64.tar.gz -C ./
          mv pandoc-2.18/bin/pandoc ./pandoc
      - name: Clone repo
        run: "gh repo clone https://github.com/ofneko/logseq-simpread.git"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert README
        run: |
          cd logseq-simpread
          ../pandoc -i README.textile -o README.html
          mv README.html README.md
      - name: Bundle Logseq dependency
        run: |
          cd logseq-simpread
          curl "https://cdn.jsdelivr.net/npm/@logseq/libs/dist/lsplugin.user.min.js" > lsplugin.user.min.js
          sed '8d' -i 'src/index.html'
          sed -e "8r lsplugin.user.min.js" -i 'src/index.html'
          sed -i '8i<script>\n' -i 'src/index.html'
          sed -i '10i</script>\n' -i 'src/index.html'
      - name: Create and upload archive 
        run: |
          cd logseq-simpread
          version=$(jq -r '.version' package.json)
          echo "Now packaging version $version…"
          zip logseq-simpread-v${version}.zip src/* LICENSE README.* package.json logo/*.svg
          gh release create v${version} logseq-simpread-v${version}.zip package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
